name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED

          # Options
          user: Ishwaranrudhara
          template: classic
          base: metadata
          config_timezone: Asia/Kolkata
          plugin_screenshot: yes
          plugin_screenshot_background: no
          plugin_screenshot_selector: body
          plugin_screenshot_title: NIFTY 50
          plugin_screenshot_url: https://www.google.com/finance/quote/NIFTY_50:INDEXNSE
